"""Assert ``scoring.py`` matches LOCOMO's upstream ``task_eval/evaluation.py``.

Expected scores were generated by running the upstream scorer on each
case (see docstring below). Any drift here means we have diverged from
the published LOCOMO metric and our F1 numbers stop being comparable to
Mem0 / Zep / MIRIX / LightMem.
"""

from __future__ import annotations

import math

import pytest

from rho.datasets.locomo.scoring import (
    extract_answer,
    f1_score,
    normalize_answer,
    score_qa,
)


# (prediction, gold, category, expected_score)
#
# Generated 2026-04-11 by running upstream
# ``task_eval/evaluation.py::eval_question_answering`` on each row.
# Do not edit these expected values without rerunning the oracle.
UPSTREAM_CASES = [
    # Category 1 (multi-hop, comma-split)
    ("Psychology, counseling certification", "Psychology, counseling certification", 1, 1.0),
    ("psychology", "Psychology, counseling certification", 1, 0.5),
    ("Adoption agencies", "Adoption agencies", 1, 1.0),
    ("Python, Go", "Python, Go", 1, 1.0),
    ("Python", "Python, Go", 1, 0.5),
    ("Go, Python", "Python, Go", 1, 1.0),
    # Category 2 (temporal, plain F1)
    ("7 May 2023", "7 May 2023", 2, 1.0),
    ("on the 7th of May 2023", "7 May 2023", 2, 0.5),
    ("RUNNING and investigating!", "runs investigated", 2, 1.0),
    ("7 May 2023", "7 May, 2023", 2, 1.0),
    # Category 3 (open-domain, semicolon-split gold, only [0] kept)
    ("Psychology; counseling; therapy", "Psychology; counseling; therapy", 3, 0.5),
    ("counseling", "Psychology; counseling; therapy", 3, 0.0),
    # Category 4 (single-hop, plain F1)
    ("mental health", "mental health", 4, 1.0),
    ("mental_health", "mental health", 4, 0.0),
    ("The answer is investigating adoption", "adoption investigation", 4, 2 / 3),
    ("the a an and test", "test", 4, 1.0),
    ("", "mental health", 4, 0.0),
]


@pytest.mark.parametrize("pred,gold,cat,expected", UPSTREAM_CASES)
def test_score_qa_matches_upstream(pred: str, gold: str, cat: int, expected: float) -> None:
    actual = score_qa(pred, gold, cat)
    assert math.isclose(actual, expected, rel_tol=1e-9, abs_tol=1e-9), (
        f"cat={cat} pred={pred!r} gold={gold!r}: got {actual} expected {expected}"
    )


def test_normalize_answer_strips_commas_before_punctuation() -> None:
    # Commas must be stripped explicitly (step 1) — they are in
    # ``string.punctuation`` but the replace(",","") happens before the
    # punctuation strip so the order is load-bearing for category 1,
    # whose f1() splits on "," BEFORE calling normalize_answer.
    assert normalize_answer("a, b, c") == "b c"  # "a" is in stopwords


def test_normalize_answer_stopwords() -> None:
    # Stopword list is {a, an, the, and} — NOT a standard NLTK set.
    assert normalize_answer("the a and an dog") == "dog"


def test_normalize_answer_removes_underscore() -> None:
    # _ is in string.punctuation and gets stripped.
    assert normalize_answer("mental_health") == "mentalhealth"


def test_f1_score_uses_porter_stem() -> None:
    # "running" stems to "run"; "runs" stems to "run" — should overlap.
    assert f1_score("running quickly", "runs quickly") == 1.0


def test_f1_score_empty_prediction_returns_zero() -> None:
    assert f1_score("", "mental health") == 0.0


def test_score_qa_rejects_category_5() -> None:
    with pytest.raises(ValueError):
        score_qa("anything", "anything", 5)


def test_extract_answer_inline() -> None:
    msg = "my reasoning goes here\n\nANSWER: Paris"
    assert extract_answer(msg) == "Paris"


def test_extract_answer_next_line() -> None:
    msg = "reasoning\n\nANSWER:\nParis\n"
    assert extract_answer(msg) == "Paris"


def test_extract_answer_last_occurrence_wins() -> None:
    msg = "ANSWER: wrong\n\nmore thought\n\nANSWER: right"
    assert extract_answer(msg) == "right"


def test_extract_answer_missing_sentinel_returns_full_message() -> None:
    msg = "just a plain answer with no sentinel"
    assert extract_answer(msg) == msg
