#!/usr/bin/env bash
set -euo pipefail

OUT="docs/cli-help.md"

{
  echo "<!-- AUTO-GENERATED by scripts/gen-cli-help.sh — do not edit -->"
  echo ""
  echo "# rho CLI reference"
  echo ""
  for cmd in "" evolve solve grade inspect select reasoningbank meta-harness ui tb2-cleanup; do
    if [ -z "$cmd" ]; then
      echo '```'
      uv run rho --help 2>/dev/null
      echo '```'
    else
      echo ""
      echo "## $cmd"
      echo ""
      echo '```'
      uv run rho "$cmd" --help 2>/dev/null
      echo '```'
    fi
  done
} > "$OUT"

echo "wrote $OUT"
