#!/usr/bin/env bash
set -euo pipefail

UPSTREAM="${1:-/tmp/letta-research/letta}"
OUT_DIR="tests/data/letta_bb52a89"
DOC="docs/research/letta-sleep-faithfulness.md"

python3 - "$UPSTREAM" "$OUT_DIR" "$DOC" <<'PY'
from __future__ import annotations

import ast
import json
import sys
from pathlib import Path

upstream = Path(sys.argv[1])
out_dir = Path(sys.argv[2])
doc_path = Path(sys.argv[3])
out_dir.mkdir(parents=True, exist_ok=True)
doc_path.parent.mkdir(parents=True, exist_ok=True)

prompt_path = upstream / "letta" / "prompts" / "system_prompts" / "sleeptime_v2.py"
group_path = upstream / "letta" / "groups" / "sleeptime_multi_agent_v4.py"
base_path = upstream / "letta" / "functions" / "function_sets" / "base.py"
constants_path = upstream / "letta" / "constants.py"


def literal_assignment(path: Path, name: str):
    module = ast.parse(path.read_text(encoding="utf-8"))
    for node in module.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == name:
                    return ast.literal_eval(node.value)
    raise KeyError(name)


def render_joined(value: ast.AST) -> str:
    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return value.value
    if isinstance(value, ast.JoinedStr):
        chunks: list[str] = []
        for part in value.values:
            if isinstance(part, ast.Constant) and isinstance(part.value, str):
                chunks.append(part.value)
            elif isinstance(part, ast.FormattedValue) and isinstance(part.value, ast.Name):
                chunks.append("{" + part.value.id + "}")
            else:
                raise TypeError(ast.dump(part))
        return "".join(chunks)
    raise TypeError(ast.dump(value))


def find_assignment_expr(path: Path, name: str) -> ast.AST:
    module = ast.parse(path.read_text(encoding="utf-8"))
    for node in ast.walk(module):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == name:
                    return node.value
    raise KeyError(name)


def function_node(module: ast.Module, name: str) -> ast.FunctionDef:
    for node in module.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            return node
    raise KeyError(name)


def value_error_sources(source: str, fn: ast.FunctionDef) -> list[str]:
    out: list[str] = []
    for node in ast.walk(fn):
        if not isinstance(node, ast.Raise):
            continue
        call = node.exc
        if not isinstance(call, ast.Call):
            continue
        if not isinstance(call.func, ast.Name) or call.func.id != "ValueError":
            continue
        if not call.args:
            continue
        segment = ast.get_source_segment(source, call.args[0])
        if segment is None:
            raise RuntimeError(f"could not get source segment for {fn.name}")
        out.append(" ".join(segment.split()))
    return out


def regex_values(fn: ast.FunctionDef) -> list[str]:
    out: list[str] = []
    for node in ast.walk(fn):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Attribute) or node.func.attr != "search":
            continue
        if len(node.args) < 1:
            continue
        arg = node.args[0]
        if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
            out.append(arg.value)
    return out


prompt = literal_assignment(prompt_path, "PROMPT")
(out_dir / "sleeptime_v2_prompt.txt").write_text(prompt, encoding="utf-8")

template = render_joined(find_assignment_expr(group_path, "message_text"))
(out_dir / "sleeptime_input_template.txt").write_text(template, encoding="utf-8")

base_source = base_path.read_text(encoding="utf-8")
base_module = ast.parse(base_source)
function_names = ["memory_replace", "memory_insert", "memory_rethink"]
faithfulness = {
    "base_sleeptime_tools": literal_assignment(constants_path, "BASE_SLEEPTIME_TOOLS"),
    "core_memory_line_number_warning": literal_assignment(
        constants_path, "CORE_MEMORY_LINE_NUMBER_WARNING"
    ),
    "validation_regexes": {},
    "value_error_sources": {},
}
for name in function_names:
    fn = function_node(base_module, name)
    faithfulness["validation_regexes"][name] = regex_values(fn)
    faithfulness["value_error_sources"][name] = value_error_sources(base_source, fn)

(out_dir / "base_memory_tool_faithfulness.json").write_text(
    json.dumps(faithfulness, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    encoding="utf-8",
)

doc_path.write_text(
    "\n".join(
        [
            "# Letta Sleep Faithfulness Snapshot",
            "",
            "Generated by `scripts/regen_letta_snapshots.sh` from `letta-ai/letta` commit `bb52a89`.",
            "",
            "Pinned artifacts:",
            "",
            "- `tests/data/letta_bb52a89/sleeptime_v2_prompt.txt`: `sleeptime_v2.py::PROMPT` value.",
            "- `tests/data/letta_bb52a89/sleeptime_input_template.txt`: `sleeptime_multi_agent_v4.py` per-invocation user message template, with `{messages_text}` in place of the runtime transcript.",
            "- `tests/data/letta_bb52a89/base_memory_tool_faithfulness.json`: `BASE_SLEEPTIME_TOOLS`, `CORE_MEMORY_LINE_NUMBER_WARNING`, validation regexes, and `ValueError` source strings from `memory_replace`, `memory_insert`, and `memory_rethink`.",
            "",
            "Intentional adaptation diff:",
            "",
            "- We run Codex instead of a Letta server.",
            "- Memory blocks are `.md` files under `harness/letta_memory/`.",
            "- The strategy adds a glossary and current-memory snapshot around the verbatim Letta prompt and user template.",
            "- `memory_finish_edits` is terminal in Letta tool rules; here it writes a sentinel and violations are logged post-hoc.",
            "",
        ]
    ),
    encoding="utf-8",
)
PY
